#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

#include "../../../../indianboy42/keymap_common.h"

#define KBD_MAPPING(X) \
    KESC(X)            \
    KQ(X)              \
    KW(X)              \
    KE(X)              \
    KR(X)              \
    KT(X)              \
    KY(X)              \
    KU(X)              \
    KI(X)              \
    KO(X)              \
    KP(X)              \
    KDEL(X)            \
    KBSPC(X)           \
    KTAB(X)            \
    KA(X)              \
    KS(X)              \
    KD(X)              \
    KF(X)              \
    KG(X)              \
    KH(X)              \
    KJ(X)              \
    KK(X)              \
    KL(X)              \
    KSCLN(X)           \
    KENT(X)            \
    KLSFT(X)           \
    KZ(X)              \
    KX(X)              \
    KC(X)              \
    KV(X)              \
    KB(X)              \
    KN(X)              \
    KM(X)              \
    KCOMM(X)           \
    KDOT(X)            \
    BTM_ROW_TRAD(X)

#define BTM_ROW_VIM(X) \
    KSLSH(X)             \
    KMO15(X)             \
    KLCTL(X)             \
    KLGUI(X)             \
    KLALT(X)             \
    KSYM(X)              \
    KSPC(X)              \
    KVLEF(X)             \
    KVDOW(X)             \
    KVUP(X)              \
    KVRGH(X)

#define BTM_ROW_TRAD(X) \
    KUP(X)               \
    KMO15(X)             \
    KLCTL(X)             \
    KLGUI(X)             \
    KLALT(X)             \
    KSYM(X)              \
    KSPC(X)              \
    KSSYM(X)             \
    KLEFT(X)             \
    KDOWN(X)             \
    KRGHT(X)

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {IB42_LAYER_TABLE(X_KEYMAP_ARRAY)};
